project:
  type: website
  output-dir: docs/
  resources:
    - "/CNAME"

website:
  title: "wuenschdirtag"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



